project: 
  type: book
  output-dir: docs_updt

author: "Dr Randy Johnson"
institute: "Hood College"
date: "last-modified"

number-depth: 1

book:
  title: "BIFX 552 - Bioinformatics Data Skills"
  subtitle: "Fall 2024"
  repo-url: "https://github.com/BIFX552-24/CourseInfo"
  repo-actions: [issue, source]
  page-footer: 
    left: |
      Copyright Randy Johnson, released under Creative Commons Attribution-ShareAlike 4.0.
  sidebar:
    collapse-level: 2
  page-navigation: true
  chapters:
    - part: Course Information
      chapters:
        - index.qmd
        - code_of_conduct.qmd
    - part: Labs
      chapters:
        - labs/01markdown.qmd
        - labs/02git.qmd
        - labs/03phacking.qmd
        - labs/04RNA-seq-data.qmd
        - labs/05COVID.qmd
        - labs/06Antibiotics-under-our-feet.qmd
        - labs/07HWE.qmd
        - labs/08Command-line-practice.qmd
        - labs/09Docker.qmd
        - labs/10Variant-calling-pipeline.qmd
    - part: Asynchronous Content
      chapters:
        - hw/H01git.qmd
        - hw/H02Intro-to-R.qmd
        - hw/H03R-basics.qmd
        - hw/H04R-programming-graphics.qmd
        - hw/H05R-advanced-data.qmd
        - hw/H06R-tables-tips.qmd
        - hw/H07Unix.qmd
        - hw/H08Snakemake.qmd
        - hw/H09VariantCalling.qmd
        - hw/H10AdvancedSnakemake.qmd

format: 
  html:
    theme: 
      light: flatly
      dark: darkly
    execute:
      echo: true
      code-fold: true
