project: 
  output-dir: docs_updt/standalone
  render: 
    - labs/01markdown.qmd
    - labs/02git.qmd
    - labs/03phacking.qmd
    - labs/04RNA-seq-data.qmd
    - labs/05COVID.qmd
    - labs/06Antibiotics-under-our-feet.qmd
    - labs/07HWE.qmd
    - labs/08Command-line-practice.qmd
    - labs/09Docker.qmd
    - labs/10Variant-calling-pipeline.qmd

author: "Dr Randy Johnson"
institute: "Hood College"

format: revealjs
