project:
  title: "BIFX-552 CourseInfo"

date: "last-modified"
author: "Dr Randy Johnson"
institute: "Hood College"

execute:
  warning: false
  cache: true

profile:
  default: book
  group: 
    - [book, slides, blackboard, docx]

editor: source
