project: 
  output-dir: docs/standalone
  render: 
    - hw/L01markdown.qmd
    - hw/L02git.qmd
    - hw/L03phacking.qmd
    - hw/L04RNA-seq-data.qmd
    - hw/L05COVID.qmd
    - hw/L06Antibiotics-under-our-feet.qmd
    - hw/L07HWE.qmd
    - hw/L08Command-line-practice.qmd
    - hw/L09Docker.qmd
    - hw/L10Variant-calling-pipeline.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
