---
title: "Midterm Exam"
---

<!--
# insert into Blackboard assignment with:
<iframe width="450" height="500" src="https://bifx552-24.github.io/CourseInfo/standalone/hw/E01midterm.html" title="Midterm Exam"></iframe>

Initial Due Date: Oct 5 @ noon
Final Due Date: Oct 12 @ end of day
Points: 100
Display after: Oct 1 @ 5 PM
Individual Assignment
-->

## Instructions

Read all instructions.

This exam is open book, open notes, and open internet, so long as you follow the guidelines in the course [Code of Conduct](https://bifx552-24.github.io/CourseInfo/code_of_conduct.html). You may not share or discuss the exam with anyone other than the instructor.

Start by accepting the [Midterm Exam](https://classroom.github.com/a/-utEpSp9) on GitHub Classroom. This will create a private repository for you to work in, including some starter code and a partial sample output. You will submit your code and answers to the questions by committing and pushing your changes to the repository. *Do not* accept pull requests on GitHub. This is how I will provide feedback on your work.

**Deadlines:** All work pushed to GitHub by noon on Oct 5 will be reviewed and returned with feedback. You may revise and resubmit your work until the **Final Due Date** of Oct 12 at the end of the day.

Your figures should be identical to those in the partial sample Word document, except in cases where you decide to use a different transformation. Additional instructions are provided in comment blocks in the provided starter code. Be sure to address each of these in your responses.

## Grading Rubric

| Deliverable   | Competency                                              | Points     |
|:--------------|:--------------------------------------------------------|:----------:|
| Code          |                                                         | 40 (total) |
|               | Renders without errors                                  | 10         |
|               | All tasks completed correctly                           |  6         |
|               | Neatness                                                |  6         |
|               | Code contains appropriate comments/documentation        |  5         |
|               | Code chunks include appropriate flags                   |  4         |
|               | Data wrangling contained in setup chunk                 |  3         |
|               | Packages loaded once in the setup chunk                 |  1         |
|               | Appropriate files pushed to GitHub                      |  5         |
|               | Proper use of pipes and vectorization                   |  5         |
| Figures       |                                                         | 30 (total) |
|               | Variables are properly transformed                      |  7         |
|               | Proper use of color and point/line types                |  7         |
|               | Labels are neat and human readable                      |  7         |
|               | Appropriate figure captions are included                |  7         |
|               | Use `theme_cowplot()`                                   |  2         |
| Word Doc      |                                                         | 15 (total) |
|               | Formatted as a Word Document                            |  5         |
|               | Code not shown in Word document                         |  5         |
|               | yaml header is updated properly                         |  5         |
| Understanding |                                                         | 15 (total) |
|               | Chosen transformation(s)                                |  5         |
|               | Written analysis                                        |  5         |
|               | Conclusions                                             |  5         |

Late exams will be subject to a 5% penalty per day after the due date, not to exceed 50%.
