---
title: "Markdown / Quarto"
date: "2024-08-20"
margin-footer: "[Slides](/standalone/labs/01markdown.html), [Assignment](/standalone/hw/L01markdown.html)"
---

<!-- 
GitHub Classroom:
  - No starter code -> empty repository when accepting the assignment
  - Individual Assignment
  - Public
  - Grant admin access
-->


## Welcome and Introductions

-   What do you hope to get from this class?
-   What was the last book that you read?

## Course Overview

-   [Blackboard](https://hood.blackboard.com/ultra/courses/_15476_1/cl/outline) tour
-   [GitHub](https://github.com/BIFX552-23) tour
-   [Syllabus](https://bifx552-24.github.io/CourseInfo)
-   [Code of Conduct](https://bifx552-24.github.io/CourseInfo/code_of_conduct)

## Today's lab

-   [Quarto](https://quarto.org/) tour.
    -   Quarto [documentation guide](https://quarto.org/docs/guide/).
    -   [Markdown basics](https://quarto.org/docs/authoring/markdown-basics.html).
    -   [Formatting code block output](https://quarto.org/docs/output-formats/html-code.html).
-   The [iris dataset](https://rpubs.com/moeransm/intro-iris).

## The iris dataset

We are going to start with the iris demo from [Rpubs.com](https://rpubs.com/moeransm/intro-iris), and then we'll go back and make some upgrades to the formatting.

:::{.content-visible when-profile="book"}
### Required
:::
:::{.content-visible when-profile="slides"}
## Required
:::

* Start by replicating the information and formatting found at <https://rpubs.com/moeransm/intro-iris> (export HTML code). Be sure to leave a note attirbuting the original authors.

* Set up a repository using [this GitHub Classroom link](https://classroom.github.com/a/VeJ0R59K) and push your code and html output to GitHub.

:::{.context-visible when-profile="slides"}
* Configure your repository to publish your webpage using [GitHub Pages](https://docs.github.com/en/pages/quickstart).

:::
:::{.content-visible when-profile="book"}
* Configure your repository to publish your webpage using [GitHub Pages](https://docs.github.com/en/pages/quickstart).
  - On step 6, select "/(root)" to publish your html code from the root directory.
  
:::

*  Export your document in [Word format](https://quarto.org/docs/output-formats/ms-word.html) and submit it on Blackboard.


:::{.content-visible when-profile="book"}
### Optional
:::
:::{.content-visible when-profile="slides"}
## Optional
:::

* Set up GitHub pages on your repository.
*  Now make it so that the user can opt for [dark mode](https://quarto.org/docs/output-formats/html-themes.html#dark-mode).
*  Turn the paragraph starting "The `summary()` function gives summary statistics for any dataset." into at tip using a [callout block](https://quarto.org/docs/authoring/callouts.html).
*  [Fold the code](https://quarto.org/docs/output-formats/html-code.html#folding-code) in the visualization section, such that only the figures are shown by default.
